name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행을 위한 옵션

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Node.js 버전
          cache: 'npm'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행 (vite build)
      - name: Build the project
        run: npm run build

      # 5. GitHub Pages 설정
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 6. 빌드된 파일 업로드 (dist 폴더)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist' # dist 폴더를 GitHub Pages에 업로드

      # 7. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
